Repository m2-modules/react, pull requests merged in 2021-09, with the labels that each got.

#5 Fix to include .* files
  plop/plopfile.js
Labels: bug

#2 Add multi action button
  .storybook/preview-head.html
  packages/multi-action-button/.gitignore
  packages/multi-action-button/.npmignore
  packages/multi-action-button/README.md
  packages/multi-action-button/__tests__/MultiActionButton.test.ts
  packages/multi-action-button/interfaces/index.ts
  packages/multi-action-button/package.json
  packages/multi-action-button/src/MultiActionButton.tsx
  packages/multi-action-button/stories/MultiActionButton.stories.tsx
  packages/multi-action-button/stories/assets/done-icon.svg
  packages/multi-action-button/tsconfig.json
  yarn.lock
Labels: new component

#11 Author 정보를 .git 디렉토리 또는 터미널을 통해 가지고 오도록
  package.json
  plop/plopfile.js
  plop/templates/component/package.json.hbs
  yarn.lock
Labels: enhancement

#12 Add outDir as exclude member
  packages/multi-action-button/tsconfig.json
  packages/ripple-effect-button/tsconfig.json
  plop/templates/component/tsconfig.json
Labels: bug

#13 Adjust eslint
  .eslintrc.js
  package.json
  packages/multi-action-button/package.json
  packages/ripple-effect-button/package.json
  plop/templates/component/package.json.hbs
  yarn.lock
Labels: enhancement

#14 Fix eslint config
  .eslintrc.json
Labels: enhancement

#15 Provide way to change more button
  packages/multi-action-button/src/MultiActionButton.tsx
  packages/multi-action-button/src/interfaces/index.ts
  packages/multi-action-button/stories/MultiActionButton.stories.tsx
Labels: enhancement

#16 Infinite list
  packages/infinite-list/.gitignore
  packages/infinite-list/.npmignore
  packages/infinite-list/README.md
  packages/infinite-list/__tests__/InfiniteList.test.ts
  packages/infinite-list/package.json
  packages/infinite-list/src/InfiniteList.tsx
  packages/infinite-list/stories/InfiniteList.stories.tsx
  packages/infinite-list/tsconfig.json
Labels: new component

#19 Fix tsconfig
  packages/infinite-list/tsconfig.json
Labels: bug

#22 Fix .npmignore
  packages/floating-label-input/.npmignore
  packages/infinite-list/.npmignore
  packages/multi-action-button/.npmignore
  packages/ripple-effect-button/.npmignore
  plop/templates/component/.npmignore
Labels: bug, enhancement

#24 Configure lerna to publish
  lerna.json
  packages/floating-label-input/package.json
  packages/infinite-list/package.json
  packages/multi-action-button/package.json
  packages/ripple-effect-button/package.json
  plop/templates/component/package.json.hbs
Labels: enhancement

#29 Refactoring to follow new structure of directory
  packages/floating-label-input/package.json
  packages/floating-label-input/src/index.ts
  packages/infinite-list/package.json
  packages/infinite-list/src/index.ts
  packages/multi-action-button/package.json
  packages/multi-action-button/src/index.ts
  packages/ripple-effect-button/package.json
  packages/ripple-effect-button/src/index.ts
Labels: bug, enhancement

#31 Adjust ripple effect option
  packages/multi-action-button/package.json
  packages/multi-action-button/src/MultiActionButton.tsx
  packages/multi-action-button/stories/MultiActionButton.stories.tsx
Labels: enhancement

#38 fix(floating-label-input): add missing dependencies, edit interface, fix eslint warning
  packages/floating-label-input/package.json
  packages/floating-label-input/src/interfaces/index.ts
  packages/floating-label-input/stories/FloatingLabelInput.stories.tsx
Labels: bug

#37 fix(ripple-effect-button): add missing dependencies
  packages/ripple-effect-button/package.json
Labels: bug

#39 Update slide-card & Remove padding of preview-header
  .storybook/preview-head.html
  packages/slide-card/.gitignore
  packages/slide-card/.npmignore
  packages/slide-card/README.md
  packages/slide-card/__tests__/SlideCard.test.ts
  packages/slide-card/package.json
  packages/slide-card/src/SlideCard.tsx
  packages/slide-card/src/index.ts
  packages/slide-card/src/interfaces/index.ts
  packages/slide-card/stories/SlideCard.stories.tsx
  packages/slide-card/tsconfig.json
Labels: new component

#40 Adjust changes of ripple effect button
  packages/multi-action-button/src/MultiActionButton.tsx
  packages/multi-action-button/src/interfaces/index.ts
  packages/multi-action-button/stories/MultiActionButton.stories.tsx
  packages/multi-action-button/stories/assets/done-icon.svg
Labels: enhancement

#47 Adjust eslint-plugin-react-hooks
  .eslintrc.json
  package.json
  yarn.lock
Labels: enhancement

#45 Add specific react version setting for eslint
  .eslintrc.json
Labels: bug

#52 feat(underline-radio-button): 밑줄 표시로 선택 표현하는 컴포넌트 개발
  packages/underline-radio-button/.gitignore
  packages/underline-radio-button/.npmignore
  packages/underline-radio-button/README.md
  packages/underline-radio-button/__tests__/UnderlineRadioButton.test.ts
  packages/underline-radio-button/package.json
  packages/underline-radio-button/src/UnderlineRadioButton.tsx
  packages/underline-radio-button/src/index.ts
  packages/underline-radio-button/src/interfaces/index.ts
  packages/underline-radio-button/stories/UnderlineRadioButton.stories.tsx
  packages/underline-radio-button/tsconfig.json
Labels: new component

#43 Improve slide card component
  packages/slide-card/src/CardIndicator.tsx
  packages/slide-card/src/SlideCard.tsx
  packages/slide-card/src/interfaces/index.ts
  packages/slide-card/src/utils/register-scroll-stop-handler.ts
  packages/slide-card/stories/SlideCard.stories.tsx
Labels: enhancement

#57 Improve infinite list
  packages/infinite-list/src/InfiniteList.tsx
  packages/infinite-list/stories/InfiniteList.stories.tsx
Labels: bug, enhancement

#55 Update draw panel component
  packages/draw-panel/.gitignore
  packages/draw-panel/.npmignore
  packages/draw-panel/README.md
  packages/draw-panel/__tests__/DrawPanel.test.ts
  packages/draw-panel/package.json
  packages/draw-panel/src/DrawPanel.tsx
  packages/draw-panel/src/index.ts
  packages/draw-panel/src/interfaces/index.ts
  packages/draw-panel/stories/DrawPanel.stories.tsx
  packages/draw-panel/tsconfig.json
Labels: new component

#60 [infinite-list] Bug fix
  packages/infinite-list/src/InfiniteList.tsx
  packages/infinite-list/stories/InfiniteList.stories.tsx
Labels: bug

#61 module property changed to target esnext
  packages/draw-panel/tsconfig.json
  packages/floating-label-input/tsconfig.json
  packages/infinite-list/tsconfig.json
  packages/multi-action-button/tsconfig.json
  packages/ripple-effect-button/tsconfig.json
  packages/slide-card/tsconfig.json
  packages/underline-radio-button/tsconfig.json
  plop/templates/component/tsconfig.json
Labels: enhancement

#63 Fix - #62
  packages/infinite-list/package.json
  packages/infinite-list/src/InfiniteList.tsx
  packages/infinite-list/src/index.ts
  packages/infinite-list/src/interfaces/index.ts
  packages/infinite-list/stories/InfiniteList.stories.tsx
Labels: bug, enhancement

#65 Update property of draw-panel & Change visibility of modal
  packages/draw-panel/src/DrawPanel.tsx
  packages/draw-panel/src/index.ts
  packages/draw-panel/src/interfaces/index.ts
Labels: bug

#66 Update modal transition property
  packages/draw-panel/src/DrawPanel.tsx
Labels: bug
